---
- name: make a build dir
  file: state=directory name=/root/zookeeper-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/zookeeper-dockerized/Dockerfile

- name: put run
  template: src=run dest=/root/zookeeper-dockerized/run mode=0755


- name: build a Docker image for Zookeeper
  docker_image:
    path:  /root/zookeeper-dockerized
    name:  gitinsky/zookeeper
    tag:   0.1.1
    state: present
  tags:
    - docker

- name: tag it as latest
  docker_image:
    path:  /root/zookeeper-dockerized
    name:  gitinsky/zookeeper
    state: build
  tags:
    - docker
