---
- name: make a build dir
  file: state=directory name=/root/zookeeper-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/zookeeper-dockerized/Dockerfile

- name: put run
  template: src=run dest=/root/zookeeper-dockerized/run mode=0755

- name: build a Docker image for Zookeeper
  command: docker build -t gitinsky/zookeeper:0.1.0 --rm /root/zookeeper-dockerized

- name: tag it as latest
  command: docker build -t gitinsky/zookeeper:latest --rm /root/zookeeper-dockerized
